#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         1
bspc config window_gap          5
#bspc config top_padding          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color "#8a6eff"
bspc config unfocused_border_color "#194D33"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar &
picom &
feh --bg-fill --randomize ~/.wallpaper/*
